version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  web:
    build: .
    command: ["rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    depends_on:
      - db
